#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 29, 2019 11:41:01 AM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import DB_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    DB_support.set_Tk_var()
    top = Toplevel1 (root)
    DB_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    DB_support.set_Tk_var()
    top = Toplevel1 (w)
    DB_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("279x229+414+149")
        top.title("Database")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.036, rely=0.087, height=21, width=20)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''ID:''')

        self.txtID = tk.Entry(top)
        self.txtID.place(relx=0.287, rely=0.087,height=20, relwidth=0.588)
        self.txtID.configure(background="white")
        self.txtID.configure(disabledforeground="#a3a3a3")
        self.txtID.configure(font="TkFixedFont")
        self.txtID.configure(foreground="#000000")
        self.txtID.configure(insertbackground="black")
        self.txtID.configure(textvariable=DB_support.txtIDVar)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.036, rely=0.218, height=21, width=45)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Krestni:''')

        self.txtKrestni = tk.Entry(top)
        self.txtKrestni.place(relx=0.287, rely=0.218,height=20, relwidth=0.588)
        self.txtKrestni.configure(background="white")
        self.txtKrestni.configure(disabledforeground="#a3a3a3")
        self.txtKrestni.configure(font="TkFixedFont")
        self.txtKrestni.configure(foreground="#000000")
        self.txtKrestni.configure(insertbackground="black")
        self.txtKrestni.configure(textvariable=DB_support.txtKrestniVar)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.036, rely=0.349, height=21, width=53)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Prijmeni:''')

        self.txtPrijmeni = tk.Entry(top)
        self.txtPrijmeni.place(relx=0.287, rely=0.349, height=20, relwidth=0.588)

        self.txtPrijmeni.configure(background="white")
        self.txtPrijmeni.configure(disabledforeground="#a3a3a3")
        self.txtPrijmeni.configure(font="TkFixedFont")
        self.txtPrijmeni.configure(foreground="#000000")
        self.txtPrijmeni.configure(insertbackground="black")
        self.txtPrijmeni.configure(textvariable=DB_support.txtPrijmeniVar)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.036, rely=0.48, height=21, width=55)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Osloveni:''')

        self.txtOsloveni = tk.Entry(top)
        self.txtOsloveni.place(relx=0.287, rely=0.48,height=20, relwidth=0.588)
        self.txtOsloveni.configure(background="white")
        self.txtOsloveni.configure(disabledforeground="#a3a3a3")
        self.txtOsloveni.configure(font="TkFixedFont")
        self.txtOsloveni.configure(foreground="#000000")
        self.txtOsloveni.configure(insertbackground="black")
        self.txtOsloveni.configure(textvariable=DB_support.txtOsloveniVar)

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.036, rely=0.611, height=21, width=42)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Mesto:''')

        self.txtMesto = tk.Entry(top)
        self.txtMesto.place(relx=0.287, rely=0.611,height=20, relwidth=0.588)
        self.txtMesto.configure(background="white")
        self.txtMesto.configure(disabledforeground="#a3a3a3")
        self.txtMesto.configure(font="TkFixedFont")
        self.txtMesto.configure(foreground="#000000")
        self.txtMesto.configure(insertbackground="black")
        self.txtMesto.configure(textvariable=DB_support.txtMestoVar)

        self.btnUpdate = tk.Button(top)
        self.btnUpdate.place(relx=0.036, rely=0.786, height=24, width=49)
        self.btnUpdate.configure(activebackground="#ececec")
        self.btnUpdate.configure(activeforeground="#000000")
        self.btnUpdate.configure(background="#d9d9d9")
        self.btnUpdate.configure(disabledforeground="#a3a3a3")
        self.btnUpdate.configure(foreground="#000000")
        self.btnUpdate.configure(highlightbackground="#d9d9d9")
        self.btnUpdate.configure(highlightcolor="black")
        self.btnUpdate.configure(pady="0")
        self.btnUpdate.configure(text='''Update''')
        self.btnUpdate.bind('<Button-1>',lambda e:DB_support.btnUpdate_Click(e))

        self.btnFirst = tk.Button(top)
        self.btnFirst.place(relx=0.394, rely=0.786, height=24, width=25)
        self.btnFirst.configure(activebackground="#ececec")
        self.btnFirst.configure(activeforeground="#000000")
        self.btnFirst.configure(background="#d9d9d9")
        self.btnFirst.configure(disabledforeground="#a3a3a3")
        self.btnFirst.configure(foreground="#000000")
        self.btnFirst.configure(highlightbackground="#d9d9d9")
        self.btnFirst.configure(highlightcolor="black")
        self.btnFirst.configure(pady="0")
        self.btnFirst.configure(text='''|<''')
        self.btnFirst.bind('<Button-1>',lambda e:DB_support.btnFirst_Click(e))

        self.btnPrev = tk.Button(top)
        self.btnPrev.place(relx=0.502, rely=0.786, height=24, width=25)
        self.btnPrev.configure(activebackground="#ececec")
        self.btnPrev.configure(activeforeground="#000000")
        self.btnPrev.configure(background="#d9d9d9")
        self.btnPrev.configure(disabledforeground="#a3a3a3")
        self.btnPrev.configure(foreground="#000000")
        self.btnPrev.configure(highlightbackground="#d9d9d9")
        self.btnPrev.configure(highlightcolor="black")
        self.btnPrev.configure(pady="0")
        self.btnPrev.configure(text='''<''')
        self.btnPrev.bind('<Button-1>',lambda e:DB_support.btnPrev_Click(e))

        self.btnNext = tk.Button(top)
        self.btnNext.place(relx=0.609, rely=0.786, height=24, width=25)
        self.btnNext.configure(activebackground="#ececec")
        self.btnNext.configure(activeforeground="#000000")
        self.btnNext.configure(background="#d9d9d9")
        self.btnNext.configure(disabledforeground="#a3a3a3")
        self.btnNext.configure(foreground="#000000")
        self.btnNext.configure(highlightbackground="#d9d9d9")
        self.btnNext.configure(highlightcolor="black")
        self.btnNext.configure(pady="0")
        self.btnNext.configure(text='''>''')
        self.btnNext.bind('<Button-1>',lambda e:DB_support.btnNext_Click(e))

        self.btnLast = tk.Button(top)
        self.btnLast.place(relx=0.717, rely=0.786, height=24, width=25)
        self.btnLast.configure(activebackground="#ececec")
        self.btnLast.configure(activeforeground="#000000")
        self.btnLast.configure(background="#d9d9d9")
        self.btnLast.configure(disabledforeground="#a3a3a3")
        self.btnLast.configure(foreground="#000000")
        self.btnLast.configure(highlightbackground="#d9d9d9")
        self.btnLast.configure(highlightcolor="black")
        self.btnLast.configure(pady="0")
        self.btnLast.configure(text='''>|''')
        self.btnLast.bind('<Button-1>',lambda e:DB_support.btnLast_Click(e))

if __name__ == '__main__':
    vp_start_gui()





