#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 29, 2019 11:41:21 AM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global txtIDVar
    txtIDVar = tk.StringVar()
    global txtKrestniVar
    txtKrestniVar = tk.StringVar()
    global txtPrijmeniVar
    txtPrijmeniVar = tk.StringVar()
    global txtOsloveniVar
    txtOsloveniVar = tk.StringVar()
    global txtMestoVar
    txtMestoVar = tk.StringVar()

def btnFirst_Click(p1):
    print('DB_support.btnFirst_Click')
    print('p1 = {0}'.format(p1))
    sys.stdout.flush()

def btnLast_Click(p1):
    print('DB_support.btnLast_Click')
    print('p1 = {0}'.format(p1))
    sys.stdout.flush()

def btnNext_Click(p1):
    print('DB_support.btnNext_Click')
    print('p1 = {0}'.format(p1))
    sys.stdout.flush()

def btnPrev_Click(p1):
    print('DB_support.btnPrev_Click')
    print('p1 = {0}'.format(p1))
    sys.stdout.flush()

def btnUpdate_Click(p1):
    print('DB_support.btnUpdate_Click')
    print('p1 = {0}'.format(p1))
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import DB
    DB.vp_start_gui()




