#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 28, 2019 01:34:47 PM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global txtHlaskaVar
    txtHlaskaVar = tk.StringVar()
    global txtKopieVar
    txtKopieVar = tk.StringVar()

def btnPozdrav(p1):
    #print('Hello_support.btnPozdrav')
    #print('p1 = {0}'.format(p1))
    #sys.stdout.flush()
    txtHlaskaVar.set("Hello World")

def btnkopy(p1):
    #print('Hello_support.btnkopy')
    #print('p1 = {0}'.format(p1))
    #sys.stdout.flush()
    txtKopieVar.set(txtHlaskaVar.get())

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Hello
    Hello.vp_start_gui()




