#! /usr/bin/env python
#
# Support module generated by PAGE version 4.8.8
# In conjunction with Tcl version 8.6
#    Feb 08, 2017 07:49:08 AM


import sys
import re  # pridano!!

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global txtRetezec
    txtRetezec = StringVar()

    global txtRegExp
    txtRegExp = StringVar()

    global lblErr
    lblErr = StringVar()


def btnTest_Click(p1):
    regExp = txtRegExp.get()
    retezec = txtRetezec.get()
    # testovani re
    p = re.compile(regExp)
    m = p.search(retezec)

    if m:
        lblErr.set("Shoda")
    else:
        lblErr.set("Chybny retezec")
    

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import RegExp
    RegExp.vp_start_gui()


