#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 30, 2018 07:36:30 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import RegExp_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    RegExp_support.set_Tk_var()
    top = Regular_expressions (root)
    RegExp_support.init(root, top)
    root.mainloop()

w = None
def create_Regular_expressions(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    RegExp_support.set_Tk_var()
    top = Regular_expressions (w)
    RegExp_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Regular_expressions():
    global w
    w.destroy()
    w = None


class Regular_expressions:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font11 = "-family {Courier New} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("782x213+650+150")
        top.title("Regular expressions")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.txtRetezec = Entry(top)
        self.txtRetezec.place(relx=0.03, rely=0.09, relheight=0.16
                , relwidth=0.95)
        self.txtRetezec.configure(background="white")
        self.txtRetezec.configure(disabledforeground="#a3a3a3")
        self.txtRetezec.configure(font=font11)
        self.txtRetezec.configure(foreground="#000000")
        self.txtRetezec.configure(highlightbackground="#d9d9d9")
        self.txtRetezec.configure(highlightcolor="black")
        self.txtRetezec.configure(insertbackground="black")
        self.txtRetezec.configure(selectbackground="#c4c4c4")
        self.txtRetezec.configure(selectforeground="black")
        self.txtRetezec.configure(textvariable=RegExp_support.txtRetezec)
        self.txtRetezec.configure(width=744)

        self.txtRegExp = Entry(top)
        self.txtRegExp.place(relx=0.03, rely=0.38, relheight=0.16, relwidth=0.95)

        self.txtRegExp.configure(background="white")
        self.txtRegExp.configure(disabledforeground="#a3a3a3")
        self.txtRegExp.configure(font=font11)
        self.txtRegExp.configure(foreground="#000000")
        self.txtRegExp.configure(highlightbackground="#d9d9d9")
        self.txtRegExp.configure(highlightcolor="black")
        self.txtRegExp.configure(insertbackground="black")
        self.txtRegExp.configure(selectbackground="#c4c4c4")
        self.txtRegExp.configure(selectforeground="black")
        self.txtRegExp.configure(textvariable=RegExp_support.txtRegExp)
        self.txtRegExp.configure(width=744)

        self.btnTest = Button(top)
        self.btnTest.place(relx=0.04, rely=0.7, height=42, width=75)
        self.btnTest.configure(activebackground="#d9d9d9")
        self.btnTest.configure(activeforeground="#000000")
        self.btnTest.configure(background="#d9d9d9")
        self.btnTest.configure(disabledforeground="#a3a3a3")
        self.btnTest.configure(font=font12)
        self.btnTest.configure(foreground="#000000")
        self.btnTest.configure(highlightbackground="#d9d9d9")
        self.btnTest.configure(highlightcolor="black")
        self.btnTest.configure(pady="0")
        self.btnTest.configure(text='''Test''')
        self.btnTest.configure(width=75)
        self.btnTest.bind('<Button-1>',lambda e:RegExp_support.btnTest_Click(e))

        self.lblErr = Label(top)
        self.lblErr.place(relx=0.18, rely=0.75, height=26, width=182)
        self.lblErr.configure(activebackground="#f9f9f9")
        self.lblErr.configure(activeforeground="black")
        self.lblErr.configure(background="#d9d9d9")
        self.lblErr.configure(disabledforeground="#a3a3a3")
        self.lblErr.configure(font=font12)
        self.lblErr.configure(foreground="#ff0000")
        self.lblErr.configure(highlightbackground="#d9d9d9")
        self.lblErr.configure(highlightcolor="black")
        self.lblErr.configure(justify=LEFT)
        self.lblErr.configure(textvariable=RegExp_support.lblErr)
        self.lblErr.configure(width=182)






if __name__ == '__main__':
    vp_start_gui()



